GET http://127.0.0.1:8000/get-csrf-token
Accept: application/json
###
DELETE http://127.0.0.1:8000/games/5
X-CSRF-TOKEN: in0I7aGHqIRjFJkHTllQT1URU1WKJ6x1NCQAIGuO
Accept: application/json
#added the token and applied accept
